# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78e4660d43fb01b6f4df9ea8747dc3c350ae6ea8f4898749ab059ad4d01ab2bb60057d1ac5242eef13f3ab935ce08c70cdc5884252cb70896820e380b76c65a8

test:
  secret_key_base: 56bbf8c781d7ed61309e157ad956e3e217ae3b07ff2ba55433447890b78b3a0e2a51fe91de20e817c472441e2d27530fbefda270454abd2dcc7d6d536f919eae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
